### ISSUE TITLE
Could this be used without server render?

### ISSUE THREAD

**Issue by qiuyuzhou** [lynndylanhurley/redux-auth#94]
I use create-react-app from facebook, which not support server render, in my project.

**Comment by betoharres** [comment]
yes, I'm using it right now, but you have to make some changes. There's some bugs in the client-side mode

**Comment by qiuyuzhou** [comment]
Thanks.

**Comment by claudicular** [comment]
What exactly do you have to change to get client side only to work? I tried the clientOnly setting and am still getting an error. 

Basically the registration confirmation link does not work for me, it throw the following error: 
Uncaught TypeError: Cannot read property 'replace' of undefined

It seems to be because it's trying to run Cookies.set on a null value for authHeaders, no idea why..

**Comment by oprearocks** [comment]
Could be a late answer but, were you using React Router v4?
